name: "Continous deployment"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone the repo"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build & push HTTP_BACKEND
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfiles/Dockerfiles.http
          push: true
          tags: aravmenon12/excalidraw:${{ github.sha }}

      - name: build & push WS_BACKEND
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfiles/Dockerfiles.ws
          push: true
          tags: aravmenon12/excalidraw:${{ github.sha }}
