name: "Continous deployment"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Clone the repo" 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Install node"
        uses: "actions/setup-node@v4"
        with: 
            node-version: "20"
        
      - run: "npm install -g pnpm"
      - run: "pnpm install"
      
